config/routes.rb
Rails.application.routes.draw do
  root to: 'questionary#index', as: 'root'
  post '/next', to: 'questionary#next', as: 'next'
  get '/graph', to: 'questionary#graph', as: 'graph'
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question
  belongs_to :questionary_session

  delegate :questinary, to: :question

  def self.aggregate_answers_for_graph
    includes(:questionary_session).
      where(questionary_sessions: {state: :done}).
      group(:answer).
      count
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :questionary
  has_many :answers
  has_many :questionary_session

  def select_answers_for_graph
    zero_hash = {}
    possible_answers.size.times do |i|
      zero_hash[possible_answers[i]] = 0
    end

    all_answers = self.answers.aggregate_answers_for_graph
    return nil if all_answers.sum {|k, v| v} == 0

    all_answers.each do |k, v|
      zero_hash[possible_answers[k]] = v
    end

    zero_hash
  end
end

app/models/questionary.rb
class Questionary < ApplicationRecord
  has_many :questions
  has_many :questionary_sessions
  has_many :answers, through: :questionary_sessions
end

app/models/questionary_session.rb
class QuestionarySession < ApplicationRecord
  belongs_to :questionary
  belongs_to :current_question, class_name: 'Question', optional: true
  has_many :questions, through: :questionary
  has_many :answers

  enum state: { ongoing: 0, done: 1}

  delegate :title, to: :questionary

  def get_question
    if self.current_question.blank?
      self.current_question = self.questions.first
      self.save
    end

    self.current_question
  end

  def total_questions
    self.questions.size
  end

  def current_question_number
    self.question_ids.index(get_question.id)
  end

  def last_question?
    current_question_number == total_questions - 1
  end

  def next_question!
    new_question = questions[current_question_number + 1]
    self.current_question = new_question
    self.save
    self.current_question
  end

  def create_answer(question, answer)
    self.answers.create(
      question: question,
      answer: answer,
      correct: answer == question.correct_answer
    )
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/questionary_controller.rb
class QuestionaryController < ApplicationController
  def index
    prepare_questionary_session
  end

  def next
    if answer_params.blank?
      flash[:notice] = 'Please Select Answer'
      return redirect_to '/'
    end

    prepare_questionary_session
    @questionary_session.create_answer(@question, answer_params['answer'].to_i)

    if @questionary_session.last_question?
      @questionary_session.done!
      redirect_to '/graph'
    else
      @question = @questionary_session.next_question!
      redirect_to '/'
    end
  end

  def graph
  end

  private

  def prepare_questionary_session
    if session['questionary_session_id'].present?
      @questionary_session = QuestionarySession.find(session['questionary_session_id'].to_i)
    else
      @questionary_session = QuestionarySession.create(questionary: Questionary.first)
      session['questionary_session_id'] = @questionary_session.id
    end

    if @questionary_session.done?
      flash[:notice] = 'Quiz was successfully finished'
      redirect_to '/graph'
    end

    @question = @questionary_session.get_question
  end

  def answer_params
    params.permit(:answer)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>QuizApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-sm bg-dark navbar-dark">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to('Quizz', root_url, class: "nav-link #{'active' if current_page?(root_url)}") %>
        </li>
        <li class="nav-item">
          <%= link_to('Graph', graph_url, class: "nav-link #{'active' if current_page?(graph_url)}") %>
        </li>
      </ul>
    </nav>

    <div class="container" style="margin-top:30px">
      <div class="row">
        <div class="col-sm-12">
          <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/questionary/graph.html.erb
<p id='notice'><%= notice %></p>

<h1>Answer distributions:</h1>
<% Questionary.all.each do |questionary| %>
  <h2><%= questionary.title %></h2>
  <% questionary.questions.each do |question| %>
    <h3><%= question.description %></h3>
    <% data_for_graph = question.select_answers_for_graph %>
    <% if !data_for_graph %>
      <strong>No Data Yet</strong>
    <% else %>
      <div class="container p-3 my-3 border">
        <%= pie_chart question.select_answers_for_graph %>
      </div>
    <% end %>
  <% end %>
<% end %>

<h1>Rectangular Graph</h1>
<% Questionary.all.each do |questionary| %>
  <h2><%= questionary.title %></h2>
  <% questionary.questions.each do |question| %>
    <h3><%= question.description %></h3>
    <% data_for_graph = question.select_answers_for_graph %>
    <% if !data_for_graph %>
      <strong>No Data Yet</strong>
    <% else %>
      <%= column_chart question.select_answers_for_graph %>
    <% end %>
  <% end %>
<% end %>

<h1>Regular Graph</h1>
<% Questionary.all.each do |questionary| %>
  <h2><%= questionary.title %></h2>
  <% questionary.questions.each do |question| %>
    <h3><%= question.description %></h3>
    <% data_for_graph = question.select_answers_for_graph %>
    <% if !data_for_graph %>
      <strong>No Data Yet</strong>
    <% else %>
      <%= line_chart question.select_answers_for_graph %>
    <% end %>
  <% end %>
<% end %>

<% content_for(:custom_javascript) do %>
  <script type="text/javascript">
    $(document).ready(function() {
      $(function() {
        $('#notice').delay(500).fadeIn('normal', function() {
          alert("11");
          $(this).delay(1500).fadeOut();
        });
      });
    });
  </script>
<% end %>

app/views/questionary/index.html.erb
<p id='notice'><%= notice %></p>

<h1><%= @questionary_session.title %></h1>

<%= form_with url: '/next' do |f| %>
  <% if @questionary_session.errors.any? %>
    <div id='error_explanation'>
      <h2><%= pluralize(@questionary_session.errors.count, 'error') %> prohibited this questionary_session from being saved:</h2>

      <ul>
        <% @questionary_session.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <h2><%= @question.description %></h2>

  <div class='container p-3 my-3 border'>
    <% @question.possible_answers.each_with_index do |answer, i| %>
      <div class='radio-box'>
        <%= f.radio_button :answer, i, class: 'custom-control-input' %>
        <%= label_tag "answer_#{i}", answer, class: 'custom-control-label' %>
      </div>
    <% end %>
  </div>

  <div class='actions row'>
    <div class='col-sm-1'>
      <%= f.submit 'Next' %>
    </div>
    <div class='col-sm-10'>
    </div>
    <div class='col-sm-1 text-right'>
      <strong>
        <%= "#{@questionary_session.current_question_number + 1} / #{@questionary_session.total_questions}" %>
      </strong>
    </div>
  </div>
<% end %>